version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sport-store-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - sportstore_sqlserver:/var/opt/mssql

volumes:
  sportstore_sqlserver:
